### ISSUE TITLE
您好，我非常需要这个数据集，能给我发一份吗？我的邮箱是ming_paper@163.com

### ISSUE THREAD

**Issue by mingmingzhu123** [CAESAR-Radi/SAR-Ship-Dataset#41]
您好，我非常需要这个数据集，能给我发一份吗？我的邮箱是ming_paper@163.com

**Comment by ErginGokkaya** [comment]
亲爱的 @mingmingzhu123，我是国际电联的博士研究生。 我的论文需要这个数据集。 如果可以，请和我分享一下吗？ 谢谢！ergingokkaya.eg@gmail.com
