### ISSUE TITLE
您好！ 感谢您的付出！我是南京大学的研究生 可以分享一下您的这个数据集吗 邮箱是huanghw1111@163.com

### ISSUE THREAD

**Issue by godencrystal** [CAESAR-Radi/SAR-Ship-Dataset#53]
谢谢您！

**Comment by erginTheDeveloper** [comment]
亲爱的，我是国际电联的博士研究生。 我的论文需要这个数据集。 如果可以，请和我分享一下吗？ 谢谢！ergingokkaya.eg@gmail.com

**Comment by ErginGokkaya** [comment]
亲爱的 @godencrystal ，我是国际电联的博士研究生。 我的论文需要这个数据集。 如果可以，请和我分享一下吗？ 谢谢！ergingokkaya.eg@gmail.com
